import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const monaSans = localFont({
  src: [
    { path: "./fonts/MonaSans-400.woff2", weight: "400", style: "normal" },
    { path: "./fonts/MonaSans-500.woff2", weight: "500", style: "normal" },
    { path: "./fonts/MonaSans-600.woff2", weight: "600", style: "normal" },
    { path: "./fonts/MonaSans-700.woff2", weight: "700", style: "normal" },
  ],
  variable: "--font-mona-sans",
  display: "swap",
  preload: false,
  fallback: ["system-ui", "sans-serif"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${monaSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
